Repository ansible-community/molecule-podman, pull requests merged in 2020-10, with the labels that each got.

#3 Restore create/destroy embedded playbooks
  .github/workflows/tox.yml
  molecule_podman/playbooks/create.yml
  molecule_podman/playbooks/destroy.yml
  tox.ini
Labels: bug

#4 Reuse molecule test requirements
  setup.cfg
  tox.ini
Labels: bug

#5 Bumped linters
  .pre-commit-config.yaml
  molecule_podman/test/__init__.py
  pyproject.toml
Labels: skip-changelog

#6 Enable py39 support
  .github/workflows/tox.yml
  setup.cfg
Labels: enhancement

#7 Added missing embedded dockerfile
  .github/workflows/tox.yml
  molecule_podman/playbooks/Dockerfile.j2
  molecule_podman/playbooks/validate-dockerfile.yml
  molecule_podman/test/test_func.py
  setup.cfg
Labels: bug

#10 Fix embedded Dockerfile location in create.yml
  molecule_podman/playbooks/create.yml
Labels: bug

#11 Avoid skipping tags
  .github/workflows/tox.yml
Labels: skip-changelog

#12 Trigger tox workflow when release is created
  .github/workflows/tox.yml
Labels: skip-changelog

#16 Moved package under lib folder
  .pre-commit-config.yaml
  .yamllint
  lib/molecule_podman/__init__.py
  lib/molecule_podman/cookiecutter/cookiecutter.json
  lib/molecule_podman/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  lib/molecule_podman/driver.py
  lib/molecule_podman/playbooks/Dockerfile.j2
  lib/molecule_podman/playbooks/create.yml
  lib/molecule_podman/playbooks/destroy.yml
  lib/molecule_podman/playbooks/validate-dockerfile.yml
  lib/molecule_podman/test/__init__.py
  lib/molecule_podman/test/conftest.py
  lib/molecule_podman/test/test_driver.py
  lib/molecule_podman/test/test_func.py
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/verify.yml
  setup.cfg
Labels: skip-changelog

#17 Verify presence of CONTAINER_HOST
  conftest.py
  lib/molecule_podman/test/conftest.py
  lib/molecule_podman/test/test_func.py
Labels: test

#20 Make driver compatible with molecule 3.2
  lib/molecule_podman/test/test_func.py
  setup.cfg
Labels: enhancement

#21 Assert run_command result
  lib/molecule_podman/test/test_func.py
Labels: skip-changelog
