Repository ansible-community/molecule-podman, pull requests merged in 2021-06, with the labels that each got.

#34 Filter verbose output of loop during Create Playbook
  lib/molecule_podman/playbooks/create.yml
Labels: enhancement

#39 Improve release-drafter config
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: skip-changelog

#40 Require containers.podman collection 1.6.1 or newer
  .pre-commit-config.yaml
  README.rst
  lib/molecule_podman/driver.py
  setup.cfg
  tox.ini
Labels: feature, major

#41 Remove publish from tox
  .github/workflows/tox.yml
Labels: skip-changelog

#36 Fixing podman flags order sequence in create task
  lib/molecule_podman/playbooks/create.yml
Labels: bug

#38 Configure podman networks
  lib/molecule_podman/playbooks/create.yml
Labels: feature

#42 Enable use of ansible-lint
  .pre-commit-config.yaml
  lib/molecule_podman/playbooks/create.yml
  lib/molecule_podman/playbooks/validate-dockerfile.yml
Labels: bug
