Repository ansible-community/molecule-podman, pull requests merged in 2021-08, with the labels that each got.

#46 Add FQCN to podman modules
  lib/molecule_podman/playbooks/create.yml
  lib/molecule_podman/playbooks/validate-dockerfile.yml
Labels: bug

#47 Rename master branch to main
  .github/workflows/release-drafter.yml
  .github/workflows/tox.yml
  README.rst
  tox.ini
Labels: bug

#48 Require containers.podman>=1.6.2
  lib/molecule_podman/driver.py
  tox.ini
Labels: bug

#49 Adopt src layout
  .pre-commit-config.yaml
  setup.cfg
  src/molecule_podman/__init__.py
  src/molecule_podman/cookiecutter/cookiecutter.json
  src/molecule_podman/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  src/molecule_podman/driver.py
  src/molecule_podman/playbooks/Dockerfile.j2
  src/molecule_podman/playbooks/create.yml
  src/molecule_podman/playbooks/destroy.yml
  src/molecule_podman/playbooks/validate-dockerfile.yml
  src/molecule_podman/test/__init__.py
  src/molecule_podman/test/conftest.py
  src/molecule_podman/test/test_driver.py
  src/molecule_podman/test/test_func.py
Labels: skip-changelog

#50 Minor workflow fixes
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: skip-changelog

#53 Allow podman executable override with env
  README.rst
  src/molecule_podman/driver.py
  src/molecule_podman/playbooks/create.yml
  src/molecule_podman/playbooks/destroy.yml
Labels: feature

#56 Add codeowners file
  .github/CODEOWNERS
Labels: skip-changelog

#57 Make functional testing more resilient
  src/molecule_podman/test/test_func.py
Labels: skip-changelog

#59 Bump linters
  .ansible-lint
  .pre-commit-config.yaml
  src/molecule_podman/playbooks/create.yml
  src/molecule_podman/playbooks/destroy.yml
Labels: skip-changelog

#62 Require molecule 3.4.0 or newer
  setup.cfg
  tox.ini
Labels: feature

#61 Enable testing with multiple ansible versions
  .github/workflows/tox.yml
  requirements.yml
  tox.ini
Labels: skip-changelog

#63 Require ansible.posix>=1.3.0
  src/molecule_podman/driver.py
Labels: bug
