Repository ansible-community/molecule-podman, pull requests merged in 2022-04, with the labels that each got.

#108 Adopt use of fqcn module names
  .pre-commit-config.yaml
  molecule/default/converge.yml
  molecule/default/verify.yml
  src/molecule_podman/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  src/molecule_podman/playbooks/create.yml
  src/molecule_podman/playbooks/destroy.yml
  src/molecule_podman/playbooks/validate-dockerfile.yml
Labels: bug, skip-changelog

#109 Bump black
  .pre-commit-config.yaml
Labels: skip-changelog

#111 Require py38 or newer
  .github/workflows/tox.yml
  mypy.ini
  setup.cfg
Labels: major

#112 Adopt check pipeline
  .github/workflows/tox.yml
Labels: skip-changelog

#114 Remove use of deprecated distutils
  src/molecule_podman/driver.py
Labels: bug

#115 More fixes
  src/molecule_podman/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  src/molecule_podman/playbooks/validate-dockerfile.yml
  tox.ini
Labels: bug

#107 Allow to additionally configure arbitrary command-line options
  src/molecule_podman/driver.py
  src/molecule_podman/playbooks/create.yml
Labels: enhancement

#118 bump gha actions/checkout to v2
  .github/workflows/tox.yml
Labels: skip-changelog, test
